ALTER TYPE "MessageKey" ADD VALUE IF NOT EXISTS 'NO_DOCTORS_FOR_SPECIALTY';
ALTER TYPE "MessageKey" ADD VALUE IF NOT EXISTS 'NO_SPECIALTIES_AVAILABLE';
ALTER TYPE "MessageKey" ADD VALUE IF NOT EXISTS 'HANDOFF_WAITING';
ALTER TYPE "MessageKey" ADD VALUE IF NOT EXISTS 'BUTTON_FAQ_LIST';
ALTER TYPE "MessageKey" ADD VALUE IF NOT EXISTS 'HEADER_SELECT_FAQ';
ALTER TYPE "MessageKey" ADD VALUE IF NOT EXISTS 'HEADER_TIME_PAGE';
